import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import Footer from "../components/Footer";

export default function TermsOfService() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  
  const homePath = localStorage.getItem("currentUser") ? "/main" : "/";
  
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0d0d0d] via-[#121212] to-[#1a1a2e] text-white flex flex-col">
      <nav className="flex justify-between items-center py-6 px-6 md:px-12 border-b border-white/10 bg-black/40 backdrop-blur-xl sticky top-0 z-50">
        <Link to="/" className="text-xl font-black bg-gradient-to-r from-[#1db954] to-[#1ed760] bg-clip-text text-transparent">
          AlgoRythms
        </Link>
        <Link to={homePath} className="text-sm font-semibold text-gray-300 hover:text-white transition-colors">
          Back to Home
        </Link>
      </nav>

      <div className="flex-1 max-w-4xl mx-auto w-full px-6 py-16">
        <h1 className="text-4xl md:text-5xl font-black mb-10 bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        
        <div className="prose prose-invert max-w-none space-y-8 text-gray-300 bg-white/5 p-8 md:p-12 rounded-3xl border border-white/10 shadow-2xl">
          <section>
            <p className="text-sm text-gray-400 mb-6">Last Updated: {new Date().toLocaleDateString()}</p>
            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="leading-relaxed">
              By accessing and using AlgoRythms ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
            <p className="leading-relaxed">
              AlgoRythms is a music discovery platform that provides song and artist recommendations using artificial intelligence and machine learning algorithms. The Service allows users to search for music, receive automated suggestions, and curate playlists.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#1db954] mb-4">3. Music Playback & Copyright (YouTube Compliance)</h2>
            <p className="leading-relaxed mb-4">
              <strong>AlgoRythms does not host, upload, or stream any copyrighted audio or video files.</strong>
            </p>
            <p className="leading-relaxed">
              All music playback functionality within the Service is provided directly via the official embedded YouTube player, utilizing the YouTube Data API v3 and YouTube Iframe API. By playing content through these embedded players, you are interacting directly with YouTube and are subject to the <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer" className="text-[#1db954] hover:underline">YouTube Terms of Service</a>. AlgoRythms acts solely as a discovery interface and does not capture, store, modify, or download the audio streams.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[#1db954] mb-4">4. Metadata Licensing (Spotify Compliance)</h2>
            <p className="leading-relaxed">
              Song titles, artist names, album art, and other contextual metadata displayed on AlgoRythms are provided by the Spotify Web API. Spotify and the Spotify logo are trademarks of Spotify AB. AlgoRythms is an independent application and is not endorsed, sponsored, or affiliated with Spotify. All metadata remains the property of Spotify or its respective licensors.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-blue-400 mb-4">5. AI Recommendations (Gemini Compliance)</h2>
            <p className="leading-relaxed">
              Our "Pro Search" and "Mood Search" features utilize the Google Gemini API to generate intelligent music recommendations. Because these results are algorithmically generated by an AI, <strong>AlgoRythms makes no guarantees regarding the accuracy, appropriateness, or exact relevance of the AI-generated results.</strong> The AI suggestions are provided "as is" for entertainment and discovery purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. AlgoRythms Plus Subscriptions</h2>
            <p className="leading-relaxed">
              Users may purchase the "AlgoRythms Plus" subscription to unlock unlimited Pro AI searches and remove daily cooldown limits. Payments are processed securely via Razorpay. By subscribing, you agree to recurring billing based on your selected plan. You may cancel your subscription at any time; however, payments already processed are subject to our Refund Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. User Accounts & Responsibilities</h2>
            <p className="leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials. You agree not to misuse the Service, including but not limited to attempting to bypass rate limits, scraping data, or using the Service to distribute illegal content. We reserve the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Limitation of Liability</h2>
            <p className="leading-relaxed">
              To the maximum extent permitted by law, AlgoRythms and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) your access to or use of or inability to access or use the Service; (b) any conduct or content of any third party on the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Changes to Terms</h2>
            <p className="leading-relaxed">
              We reserve the right to modify these Terms of Service at any time. We will provide notice of significant changes by updating the date at the top of this page. Your continued use of the Service following any changes constitutes your acceptance of the new terms.
            </p>
          </section>
        </div>
      </div>
      
      <Footer />
    </div>
  );
}
